### ISSUE TITLE
No tegra21_hdmi2csi_defconfig

### ISSUE THREAD

**Issue by wilkinsw** [InES-HPMM/linux-l4t-4.4-kernel#1]
The TX2 hdmi2csi defconfig does not exist in the l4t-r28.2.1 branch
https://github.com/InES-HPMM/linux-l4t-4.4-kernel/tree/hdmi2csi/l4t-r28.2.1/arch/arm64/configs

**Comment by dariis** [comment]
The new branch is only tested on TX2 and the defconfig is  [`tegra18_hdmi2csi_defconfig`](https://github.com/InES-HPMM/linux-l4t-4.4-kernel/blob/hdmi2csi/l4t-r28.2.1/arch/arm64/configs/tegra18_hdmi2csi_defconfig).

tegra18 --> TX2
tegra21 --> TX1
